volumes:
  db:

services:
  db:
    image: postgres:13.6-alpine
    env_file:
    - .env
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: enceladus
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
    - 5432:5432
    restart: always
    volumes:
    - db:/var/lib/postgresql/data
    - ./curious_data/data:/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      retries: 5
